---
abstract: 'map relational database to RDF declaratively'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  DBD::SQLite: 0
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
keywords:
  - Perl
  - RDF
  - Turtle
  - R2RML
  - RDB2RDF
  - SQL
  - Database
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RDF-RDB2RDF
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  DBI: 0
  DBIx::Admin::TableInfo: 0
  Data::UUID: 0
  JSON: 0
  MIME::Base64: 0
  RDF::Trine: 0.133
  Scalar::Util: 0
  Storable: 0
  URI::Escape: 0
  common::sense: 0
  namespace::clean: 0
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=RDF-RDB2RDF
  homepage: https://metacpan.org/release/RDF-RDB2RDF
  license: http://dev.perl.org/licenses/
  repository: http://goddamn.co.uk/svn-web/perlmods/browse/RDF-RDB2RDF/
version: 0.004

