# This file provides instructions for packaging.

@prefix : <http://purl.org/NET/cpan-uri/terms#> .

<http://purl.org/NET/cpan-uri/dist/RDF-RDB2RDF/project>
	:perl_version_from _:main ;
	:version_from _:main ;
	:readme_from _:main ;
	:test_requires
		"DBD::SQLite" ,
		"Test::More 0.61" ;
	:requires 
		"Carp" ,
		"common::sense" ,
		"Data::UUID" ,
		"DBI" ,
		"DBIx::Admin::TableInfo" ,
		"JSON" ,
		"MIME::Base64" ,
		"namespace::clean" ,
		"RDF::Trine 0.133" ,
		"Scalar::Util" ,
		"Storable" ,
		"URI::Escape" .

_:main <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName> "lib/RDF/RDB2RDF.pm" .

